src/Entity/LogConges.php
<?php

namespace App\Entity;

use App\Repository\LogCongesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LogCongesRepository::class)]
class LogConges
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'logConges')]
    private ?Conges $conges = null;

    #[ORM\ManyToOne(inversedBy: 'logConges')]
    private ?User $User = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $detail = null;

    #[ORM\ManyToOne(inversedBy: 'logCongesInitiative')]
    private ?User $userInitiative = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getConges(): ?Conges
    {
        return $this->conges;
    }

    public function setConges(?Conges $conges): static
    {
        $this->conges = $conges;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): static
    {
        $this->User = $User;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(?string $detail): static
    {
        $this->detail = $detail;

        return $this;
    }

    public function getUserInitiative(): ?User
    {
        return $this->userInitiative;
    }

    public function setUserInitiative(?User $userInitiative): static
    {
        $this->userInitiative = $userInitiative;

        return $this;
    }
}

templates/_partials/_errorPage.html.twig
{% block title %}{% endblock %}

{% block body %}
    {% for message in app.flashes('error') %}
    
        <div class="flash-message flash-error">
            {{ message }}
        </div>
    {% endfor %}

 
    <style>
       
    </style>

<!-- Pour effacer le message au bout de 5 secondes -->
     <script>
        document.addEventListener('DOMContentLoaded', function() {
            const flashMessages = document.querySelectorAll('.flash-message');
            setTimeout(() => {
                flashMessages.forEach(message => {
                    message.style.opacity = '0';
                    setTimeout(() => {
                        message.remove();
                    }, 500); 
                });
            }, 5000);  
        });
    </script> 
{% endblock %}

templates/_partials/_nav.html.twig
{% if app.user %}
<div class="topbar-container topbar">
    <div id="profilUser" >👤{{ userConnecter.username }}
</div>
    <div class="topbar">
        <div class="topbar-inner">
            <nav class="topbar-nav">
                <a href="{{ path('app_home') }}" class="tab {{ page == 'calendrier' ? 'active' : '' }}">Calendrier</a>
                <a href="{{ path('app_conges_crud_index') }}" class="tab {{ page == 'conges' ? 'active' : '' }}">Mes
                    congés</a>
                {% if is_granted('ROLE_ADMIN') %}
                <a href="{{ path('app_conges_demande') }}"
                    class="tab {{ page == 'demande' ? 'active' : '' }}">Demandes</a>
                <a href="{{ path('app_admin_panel') }}" class="tab {{ page == 'panel' ? 'active' : '' }}">Panel
                    ADMIN</a>
                {% endif %}
            </nav>
        </div>
    </div>

</div>

    <style>
        .tab
        {
            position: relative;
            z-index: 0;
        }


        .tab:before
        {
            position: absolute;
            width: 100%;
            height: 2px;
            left: 0px;
            bottom: 0px;
            content: '';
            background: #F4F6F9;
            opacity: 0.3;
            transition: all 0.3s;
        }

        .tab:hover:before
        {
            height: 100%;
        }
    </style>

{% endif %}

templates/_partials/_successPage.html.twig
{% block title %}{% endblock %}

{% block body %}
    {% for message in app.flashes('info') %}
        <div class="flash-message flash-success">

            {{ message }}
        </div>
    {% endfor %}

 
    <style>
       
    </style>

<!-- Pour effacer le message au bout de 5 secondes -->
     <script>
        document.addEventListener('DOMContentLoaded', function() {
            const flashMessages = document.querySelectorAll('.flash-message');
            setTimeout(() => {
                flashMessages.forEach(message => {
                    message.style.opacity = '0';
                    setTimeout(() => {
                        message.remove();
                    }, 500); 
                });
            }, 5000); 
        });
    </script> 
{% endblock %}